### PR TITLE
Add textproto as a valid ClangFormat file

### PR DESCRIPTION
**Pull request by agasparovic-sabre**
ClangFormat recognizes .textproto files and will format in TextProto format.

### CODE REVIEW

**Comment by agasparovic-sabre** [comment]
Thanks a lot for making this Pre-Commit check, by the way!

**Comment by agasparovic-sabre** [comment]
Hi all, let me know if there's anything else I should do to make this easier to review! Happy to update as needed.

**Comment by agasparovic-sabre** [comment]
Hi all, any update? Thanks!

**Comment by agasparovic-sabre** [comment]
Gentle ping on this review...

**Review by ghost — APPROVED** [review]

**Comment by agasparovic-sabre** [comment]
Thanks a lot!

**Pull request merged**
